version: '3'
services:
  server:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: /opt/sqlite/data.db
        target: /app/backend/config/data.db 
    ports:
      - "8080:8080"
  
  client:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "12880:12880"
      
    
